### ISSUE TITLE
3 Errors of "presentDefaultExpandedMediaControls"

### ISSUE THREAD

**Issue by xtreme8210** [googlecast/CastRemoteDisplay-iOS#10]
Hi
GCKCastContext.h doesn't have this method "presentDefaultExpandedMediaControls".
Please Help me
![2016-08-09 2 29 29](https://cloud.githubusercontent.com/assets/2245528/17506756/05f8dd86-5e3e-11e6-834f-d750ea8d1c84.png)

**Comment by entertailion** [comment]
Make sure you have the 3.1.1 version of the iOS Cast SDK.
