### ISSUE TITLE
Error in compiling RootViewController.m  ARC semantic issue

### ISSUE THREAD

**Issue by sensei71** [googlecast/CastRemoteDisplay-iOS#3]
error in RootViewController.m:56:34: No known class method for selector 'audioFilePlayerWithURL:audioController:error:'

original code line

self.loop = [AEAudioFilePlayer audioFilePlayerWithURL:file
                                        audioController:_audioController
                                                  error:NULL];

**Comment by ianbarber** [comment]
Fixed in #4
