### ISSUE TITLE
AAE Sound effects terrible sound

### ISSUE THREAD

**Issue by holyspidoo** [googlecast/CastRemoteDisplay-iOS#7]
I'm sure I'm at fault, but I'm trying to get a sound effect playing everytime I push a button on the phone 
through remote display.

It is a short clip (4-5 seconds). It sounds terrible about 75% of the time

Maybe I'm not using the workaround well in Swift?

```
let cracklingSoundWorkaroundStereo = AudioStreamBasicDescription(
            mSampleRate: k48kHZ,
            mFormatID: kAudioFormatLinearPCM,
            mFormatFlags: kAudioFormatFlagIsFloat | kAudioFormatFlagIsPacked |
            kAudioFormatFlagIsNonInterleaved,
            mBytesPerPacket: UInt32(sizeof(Float)),
            mFramesPerPacket: 1,
            mBytesPerFrame: UInt32(sizeof(Float)),
            mChannelsPerFrame: 2,
            mBitsPerChannel: 8*UInt32(sizeof(Float)),
            mReserved: 1)
```

**Comment by holyspidoo** [comment]
Basically, it happens in the first seconds of any audio playback about 75% of the time. If you start music, of course you don't notice it, if you loop, you don't notice it.

But if you play a short audio clip (4-5 secs) once (or many times with a button), the issue is there.

**Comment by chrisrecher** [comment]
I'll start investigating this and publish my findings on [StackOverflow](http://stackoverflow.com/questions/35096863/remote-display-ios-play-a-sound-more-than-once-garbled), as this isn't an issue with this sample app itself.
